{
  account(id: "GCVIRZIN4CGYY56CSL7RYAFHKQTGE34GIASZ2D4IGZGV3FDL622LPQZT") {
    flags {
      authRequired
      authRevokable
      authImmutable
    }
    thresholds {
      masterWeight
      low
      medium
      high
    }
    id
    inflationDestination { id }
    sequenceNumber
    data {
      name
      value
    }
    signers {
      signer
    }
    trustLines {
      account {
        id
      }
      asset {
        code
        native
        issuer { id }
      }
    }
    ledger {
      seq
      header {
        ledgerVersion
      }
    }
  }
}
