{
  accountsSignedBy(
    id:"GAJXMD3UHZWTW6SC2XLT2GPUL5DXJFCW7KLNM7J5KQMN53M3QQQL7HJ4",
    first: 20
  ) {
    id
    signers {
      weight
      account {
        id
      }
    }
    trustLines {
      asset {
        code
      }
      authorized
    }
    ledger {
      seq
    }
  }
}
